#!/usr/bin/env bash
tee .env << EOF
MARIADB_HOST="$MARIADB_HOST"
MARIADB_PORT="$MARIADB_PORT"
MARIADB_DATABASE="$MARIADB_DATABASE"
MARIADB_USER="$MARIADB_USER"
MARIADB_PASSWORD="$MARIADB_PASSWORD"
MD5_SALT="$MD5_SALT"
DEFAULT_TIMEZONE="$DEFAULT_TIMEZONE"
COLOR_THEMES="$COLOR_THEMES"
ENABLE_POO="$ENABLE_POO"
POO_EXPIRY_TIME="$POO_EXPIRY_TIME"
TG_ENABLE="$TG_ENABLE"
TG_CHANNEL_APPROVED="$TG_CHANNEL_APPROVED"
HOME_FAVICON="$HOME_FAVICON"
COPYRIGHT_MSG="$COPYRIGHT_MSG"
FAVORITES_ICON="$FAVORITES_ICON"
APPROVED_ICON="$APPROVED_ICON"
ALL_ICON="$ALL_ICON"
META_DESCRIPTION="$META_DESCRIPTION"
META_KEYWORDS="$META_KEYWORDS"
SRV_HOST="$SRV_HOST"
SRV_PORT="$SRV_PORT"
REDIS_HOST="$REDIS_HOST"
REDIS_PORT="$REDIS_PORT"
SPHINX_HOST="$SPHINX_HOST"
SPHINX_PORT="$SPHINX_PORT"
RSS_MANAGING_EDITOR="$RSS_MANAGING_EDITOR"
RSS_CHANNEL_DESCRIPTION="$RSS_CHANNEL_DESCRIPTION"
CSS_VERSION="$CSS_VERSION"
JS_VERSION="$JS_VERSION"
ICONS_VERSION="$ICONS_VERSION"
EOF
  for ARGS in $@; do
	    case $ARGS in    
	        "install")     cd ./scripts; npm run installation;;
	    esac
  done
    if [[ -z $@ ]]; then
        php-fpm7.4 -O -F --fpm-config ./scripts/config/php-fpm.conf &
        cd ./scripts
        npm start
    fi
