services: 
  db:
    image: mariadb:11.6
    container_name: db
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - 1chan

  1chan:
    build:
      context: .
      dockerfile: ./docker/1chan.Dockerfile
    container_name: 1chan
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_HOST: "db"
      MARIADB_PORT: "3306"
      SRV_HOST: "1chan-service"
      SRV_PORT: "9393"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      SPHINX_HOST: "1chan-service"
      SPHINX_PORT: "3312"
      CSS_VERSION: "?1"
      JS_VERSION: "?1"
      ICONS_VERSION: "?1"
    ports:
      - "80:80"
    volumes:
      - www-img:/src/www/img
      - www-ico:/src/www/ico
      - www-uploads:/src/www/uploads
    networks:
      - 1chan
    depends_on:
      - 1chan-service

  1chan-service:
    build:
      context: .
      dockerfile: ./docker/1chan-service.Dockerfile
    container_name: 1chan-service
    restart: on-failure
    env_file:
      - .env
    environment:
      MARIADB_HOST: "db"
      MARIADB_PORT: "3306"
      SRV_HOST: "0.0.0.0"
      SRV_PORT: "9393"
      SRV_LOCAL_HOST: "1chan-service"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      SPHINX_HOST: "0.0.0.0"
      SPHINX_PORT: "3312"
      SPHINX_DATA_DIR: "/var/lib/sphinxsearch"
      SPHINX_BIN_DIR: "/usr/bin"
      INDEXER_MEM_LIMIT: "64M"
      INDEXER_MAX_IOPS: "40"
      SEARCHD_START: "true"
      SEARCHD_LOG_FILE: "searchd.log"
      SEARCHD_READ_TIMEOUT: "5"
      SEARCHD_MAX_CHILDREN: "30"
      SEARCHD_PID_FILE: "searchd.pid"
    volumes:
      - www-img:/src/www/img
      - www-ico:/src/www/ico
      - www-uploads:/src/www/uploads
    networks:
      - 1chan
    depends_on:
      db:
        condition: service_started
        restart: false
      redis:
        condition: service_started
        restart: false

  torgate:
    build:
      context: .
      dockerfile: ./docker/torgate.Dockerfile
    container_name: torgate
    environment:
      TORGATE_ENDPOINT: "1chan:80"
    env_file:
      - .env
    networks:
      - 1chan
    depends_on:
      1chan:
        condition: service_started
        restart: false

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - 1chan

volumes:
  mariadb_data:
  redis_data:
  www-img:
  www-ico:
  www-uploads:

networks:
  1chan:
