services:
  app:
    build: ./frontend
    container_name: app
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_HOST: "db"
      MARIADB_PORT: "3306"
      SRV_HOST: "127.0.0.1"
      SRV_PORT: "9393"
      SRV_LOCAL_HOST: "127.0.0.1"
      REDIS_HOST: "cache"
      REDIS_PORT: "6379"
      SPHINX_HOST: "127.0.0.1"
      SPHINX_PORT: "3312"
      SPHINX_DATA_DIR: "/var/lib/sphinxsearch"
      SPHINX_BIN_DIR: "/usr/bin"
      INDEXER_MEM_LIMIT: "64M"
      INDEXER_MAX_IOPS: "40"
      SEARCHD_START: "true"
      SEARCHD_LOG_FILE: "searchd.log"
      SEARCHD_READ_TIMEOUT: "5"
      SEARCHD_MAX_CHILDREN: "30"
      SEARCHD_PID_FILE: "searchd.pid"
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - www-smilies:/src/www/img/smilies
      - www-homeboards:/src/www/ico/homeboards
      - www-uploads:/src/www/uploads
      - sphinxsearch_data:/var/lib/sphinxsearch
    networks:
      - 1chan
    depends_on:
      - db
      - cache

  db:
    image: mariadb:11.6
    container_name: db
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - 1chan

  cache:
    image: redis:7-alpine
    container_name: cache
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - cache_data:/data
    networks:
      - 1chan

  torgate:
    build: ./torgate
    container_name: torgate
    depends_on:
      app:
        condition: service_started
        restart: false
    env_file:
      - .env
    networks:
      - 1chan

  i2pgate:
    build: ./i2pgate
    container_name: i2pgate
    depends_on:
      app:
        condition: service_started
        restart: false
    env_file:
      - .env
    networks:
      - 1chan

  yggdrasilgate:
    build: ./yggdrasilgate
    container_name: yggdrasilgate
    depends_on:
      app:
        condition: service_started
        restart: false
    env_file:
      - .env
    networks:
      - 1chan
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"

volumes:
  mariadb_data:
  cache_data:
  www-smilies:
  www-homeboards:
  www-uploads:
  sphinxsearch_data:

networks:
  1chan:
