services: 
  db:
    image: mariadb:11.6
    container_name: db
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - 1chan

  1chan:
    build: .
    container_name: 1chan
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_HOST: "db"
      MARIADB_PORT: "3306"
      SRV_HOST: "127.0.0.1"
      SRV_PORT: "9393"
      SRV_LOCAL_IP: "127.0.0.1"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      SPHINX_HOST: "127.0.0.1"
      SPHINX_PORT: "3312"
      SPHINX_DATA_DIR: "/var/lib/sphinxsearch"
      SPHINX_BIN_DIR: "/usr/bin"
      INDEXER_MEM_LIMIT: "64M"
      INDEXER_MAX_IOPS: "40"
      SEARCHD_START: "true"
      SEARCHD_LOG_FILE: "searchd.log"
      SEARCHD_READ_TIMEOUT: "5"
      SEARCHD_MAX_CHILDREN: "30"
      SEARCHD_PID_FILE: "searchd.pid"
      CSS_VERSION: "?1"
      JS_VERSION: "?1"
      ICONS_VERSION: "?1"
    ports:
      - "80:80"
    networks:
      - 1chan
    depends_on:
      - db
      - redis

  redis:
    image: redis:7
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - 1chan

volumes:
  mariadb_data:
  redis_data:

networks:
  1chan:
