services: 

  db:
    image: mariadb:11.6
    container_name: db
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - bridge

  onechan:
    build:
      context: .
      dockerfile: ./docker/1chan.Dockerfile
    container_name: onechan
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_HOST: "db"
      MARIADB_PORT: "3306"
      SRV_HOST: "127.0.0.1"
      SRV_PORT: "9393"
      SRV_LOCAL_HOST: "127.0.0.1"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      SPHINX_HOST: "127.0.0.1"
      SPHINX_PORT: "3312"
      SPHINX_DATA_DIR: "/var/lib/sphinxsearch"
      SPHINX_BIN_DIR: "/usr/bin"
      INDEXER_MEM_LIMIT: "64M"
      INDEXER_MAX_IOPS: "40"
      SEARCHD_START: "true"
      SEARCHD_LOG_FILE: "searchd.log"
      SEARCHD_READ_TIMEOUT: "5"
      SEARCHD_MAX_CHILDREN: "30"
      SEARCHD_PID_FILE: "searchd.pid"
    ports:
      - "80:80"
    volumes:
      - www-smilies:/src/www/img/smilies
      - www-homeboards:/src/www/ico/homeboards
      - www-uploads:/src/www/uploads
      - sphinxsearch_data:/var/lib/sphinxsearch
    networks:
      - bridge
    depends_on:
      - db
      - redis

  torgate:
    build:
      context: .
      dockerfile: ./docker/torgate.Dockerfile
    container_name: torgate
    depends_on:
      onechan:
        condition: service_started
        restart: false
    env_file:
      - .env
    networks:
      - bridge
        
  i2pgate:
    build:
      context: .
      dockerfile: ./docker/i2pgate.Dockerfile
    container_name: i2pgate
    depends_on:
      onechan:
        condition: service_started
        restart: false
    env_file:
      - .env
    networks:
      - bridge
        
  yggdrasil:
    build:
      context: .
      dockerfile: ./docker/yggdrasil.Dockerfile
    container_name: yggdrasil
    depends_on:
      onechan:
        condition: service_started
        restart: false
    env_file:
      - .env
    networks:
      - bridge
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - bridge

volumes:
  mariadb_data:
  redis_data:
  www-smilies:
  www-homeboards:
  www-uploads:
  sphinxsearch_data:

networks:
  bridge:
