apiVersion: v1
kind: Service
metadata:
  name: frontend-1chan-expose
  namespace: onechan-dev
spec:
  ports:
  - name: onechan
    port: 80
    targetPort: 80
  externalTrafficPolicy: Local
  selector:
    part-of: lb
  type: LoadBalancer
