apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-1chan
  namespace: onechan
spec:
  ingressClassName: nginx
  rules:
  - host: 1chan.cyou
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: onechan
            port:
              number: 80
