apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-1chan
  namespace: onechan
  annotations:
    nginx.ingress.kubernetes.io/enable-real-ip: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For, X-Real-IP"
spec:
  ingressClassName: nginx
  rules:
  - host: 1chan.cyou
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: onechan
            port:
              number: 80
