apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-1chan
  namespace: onechan-dev
spec:
  ingressClassName: nginx
  rules:
  - host: dev.1chan.cyou
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
