apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: 1chan-sc
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
