apiVersion: apps/v1
items:

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: {{ .Release.Name }}-{{ .Values.svc.onechan.name }}
    namespace: {{ .Release.Namespace }}
  spec:
    replicas: {{ .Values.svc.onechan.image.replicas }}
    selector:
      matchLabels:
        app: {{ .Values.svc.onechan.name }}
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
    template:
      metadata:
        labels:
          app: {{ .Values.svc.onechan.name }}
          part-of: lb
      spec:
        hostname: {{ .Values.svc.onechan.name }}
        restartPolicy: {{ .Values.restartPolicy }}
        {{- include "ImagePullSecret" . | nindent 8 }}
        initContainers:
        - name: wait-db-and-redis
          image: alpine/curl
          imagePullPolicy: IfNotPresent
          command:
          - sh
          - -c
          - |
            until curl http://{{ .Values.svc.db.name }}:3306 2>&1 | grep -q "1" && \
              curl http://{{ .Values.svc.redis.name }}:6379 2>&1 | grep -q "52"; do 
              sleep 1
            done
        containers:
        - name: {{ .Values.svc.onechan.image.name }}
          image: {{ include "ImageRegistry" . }}/{{ .Values.svc.onechan.image.name }}:{{ .Values.svc.onechan.image.tag }}
          imagePullPolicy: {{ .Values.svc.onechan.image.pullPolicy }}
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 81
            protocol: TCP
          env:
          - name: MARIADB_HOST
            value: {{ .Values.svc.db.name }}
          - name: MARIADB_PORT
            value: "3306"
          - name: SRV_HOST
            value: "127.0.0.1"
          - name: SRV_PORT
            value: "9393"
          - name: SRV_LOCAL_HOST
            value: "127.0.0.1"
          - name: REDIS_HOST
            value: {{ .Values.svc.redis.name }}
          - name: REDIS_PORT
            value: "6379"
          - name: SPHINX_HOST
            value: "127.0.0.1"
          - name: SPHINX_PORT
            value: "3312"
          - name: SPHINX_DATA_DIR
            value: "/var/lib/sphinxsearch"
          - name: SPHINX_BIN_DIR
            value: "/usr/bin"
          - name: INDEXER_MEM_LIMIT
            value: "64M"
          - name: INDEXER_MAX_IOPS
            value: "40"
          - name: SEARCHD_START
            value: "true"
          - name: SEARCHD_LOG_FILE
            value: "searchd.log"
          - name: SEARCHD_READ_TIMEOUT
            value: "5"
          - name: SEARCHD_MAX_CHILDREN
            value: "30"
          - name: SEARCHD_PID_FILE
            value: "searchd.pid"
          - name: CSS_VERSION
            valueFrom:
              secretKeyRef:
                key: CSS_VERSION
                name: {{ include "SecretsName" . }}
          - name: JS_VERSION
            valueFrom:
              secretKeyRef:
                key: JS_VERSION
                name: {{ include "SecretsName" . }}
          - name: ICONS_VERSION
            valueFrom:
              secretKeyRef:
                key: ICONS_VERSION
                name: {{ include "SecretsName" . }}
          - name: ADMIN_LOGIN
            valueFrom:
              secretKeyRef:
                key: ADMIN_LOGIN
                name: {{ include "SecretsName" . }}
          - name: ADMIN_PASSWD
            valueFrom:
              secretKeyRef:
                key: ADMIN_PASSWD
                name: {{ include "SecretsName" . }}
          - name: MARIADB_DATABASE
            valueFrom:
              secretKeyRef:
                key: MARIADB_DATABASE
                name: {{ include "SecretsName" . }}
          - name: MARIADB_USER
            valueFrom:
              secretKeyRef:
                key: MARIADB_USER
                name: {{ include "SecretsName" . }}
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MARIADB_PASSWORD
                name: {{ include "SecretsName" . }}
          - name: MD5_SALT
            valueFrom:
              secretKeyRef:
                key: MD5_SALT
                name: {{ include "SecretsName" . }}
          - name: CHANNEL_SALT
            valueFrom:
              secretKeyRef:
                key: CHANNEL_SALT
                name: {{ include "SecretsName" . }}
          - name: SIO_TOKEN
            valueFrom:
              secretKeyRef:
                key: SIO_TOKEN
                name: {{ include "SecretsName" . }}
          - name: WEB_DOMAIN
            valueFrom:
              secretKeyRef:
                key: WEB_DOMAIN
                name: {{ include "SecretsName" . }}
          - name: DEFAULT_TIMEZONE
            valueFrom:
              secretKeyRef:
                key: DEFAULT_TIMEZONE
                name: {{ include "SecretsName" . }}
          - name: COLOR_THEMES
            valueFrom:
              secretKeyRef:
                key: COLOR_THEMES
                name: {{ include "SecretsName" . }}
          - name: COMMON_ROOM_CONTROLWORD
            valueFrom:
              secretKeyRef:
                key: COMMON_ROOM_CONTROLWORD
                name: {{ include "SecretsName" . }}
          - name: TORGATE_HOSTNAME
            valueFrom:
              secretKeyRef:
                key: TORGATE_HOSTNAME
                name: {{ include "SecretsName" . }}
                optional: true
          - name: ENABLE_POO
            valueFrom:
              secretKeyRef:
                key: ENABLE_POO
                name: {{ include "SecretsName" . }}
                optional: true
          - name: POO_EXPIRY_TIME
            valueFrom:
              secretKeyRef:
                key: POO_EXPIRY_TIME
                name: {{ include "SecretsName" . }}
                optional: true
          - name: RATE_BUTTON_ORDER
            valueFrom:
              secretKeyRef:
                key: RATE_BUTTON_ORDER
                name: {{ include "SecretsName" . }}
          - name: TG_ENABLE
            valueFrom:
              secretKeyRef:
                key: TG_ENABLE
                name: {{ include "SecretsName" . }}
                optional: true
          - name: TG_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                key: TG_BOT_TOKEN
                name: {{ include "SecretsName" . }}
                optional: true
          - name: TG_CHANNEL_ALL
            valueFrom:
              secretKeyRef:
                key: TG_CHANNEL_ALL
                name: {{ include "SecretsName" . }}
                optional: true
          - name: TG_CHANNEL_APPROVED
            valueFrom:
              secretKeyRef:
                key: TG_CHANNEL_APPROVED
                name: {{ include "SecretsName" . }}
                optional: true
          - name: HOME_FAVICON
            valueFrom:
              secretKeyRef:
                key: HOME_FAVICON
                name: {{ include "SecretsName" . }}
          - name: COPYRIGHT_MSG
            valueFrom:
              secretKeyRef:
                key: COPYRIGHT_MSG
                name: {{ include "SecretsName" . }}
          - name: FAVORITES_ICON
            valueFrom:
              secretKeyRef:
                key: FAVORITES_ICON
                name: {{ include "SecretsName" . }}
          - name: APPROVED_ICON
            valueFrom:
              secretKeyRef:
                key: APPROVED_ICON
                name: {{ include "SecretsName" . }}
          - name: ALL_ICON
            valueFrom:
              secretKeyRef:
                key: ALL_ICON
                name: {{ include "SecretsName" . }}
          - name: META_DESCRIPTION
            valueFrom:
              secretKeyRef:
                key: META_DESCRIPTION
                name: {{ include "SecretsName" . }}
          - name: META_KEYWORDS
            valueFrom:
              secretKeyRef:
                key: META_KEYWORDS
                name: {{ include "SecretsName" . }}
          - name: RSS_MANAGING_EDITOR
            valueFrom:
              secretKeyRef:
                key: RSS_MANAGING_EDITOR
                name: {{ include "SecretsName" . }}
          - name: RSS_CHANNEL_DESCRIPTION
            valueFrom:
              secretKeyRef:
                key: RSS_CHANNEL_DESCRIPTION
                name: {{ include "SecretsName" . }}
          - name: INDEXER_SCHEDULE
            valueFrom:
              secretKeyRef:
                key: INDEXER_SCHEDULE
                name: {{ include "SecretsName" . }}
          - name: SERVER_STATUS_SCHEDULE
            valueFrom:
              secretKeyRef:
                key: SERVER_STATUS_SCHEDULE
                name: {{ include "SecretsName" . }}
          - name: SERVER_STATUS_PROXY
            valueFrom:
              secretKeyRef:
                key: SERVER_STATUS_PROXY
                name: {{ include "SecretsName" . }}
          - name: SERVER_STATUS_TIMEOUT
            valueFrom:
              secretKeyRef:
                key: SERVER_STATUS_TIMEOUT
                name: {{ include "SecretsName" . }}
          volumeMounts:
          - name: {{ .Values.svc.onechan.name }}-www-pv
            mountPath: /src/www/img/smilies
            subPath: www-smilies
          - name: {{ .Values.svc.onechan.name }}-www-pv
            mountPath: /src/www/ico/homeboards
            subPath: www-homeboards
          - name: {{ .Values.svc.onechan.name }}-www-pv
            mountPath: /src/www/uploads
            subPath: www-uploads
          - name: {{ .Values.svc.onechan.name }}-www-pv
            mountPath: /var/lib/sphinxsearch
            subPath: sphinxsearch_data
        volumes:
        - name: {{ .Values.svc.onechan.name }}-www-pv
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ .Values.svc.onechan.name }}-www-pvc

- apiVersion: v1
  kind: Service
  metadata:
    name: {{ .Values.svc.onechan.name }}
    namespace: {{ .Release.Namespace }}
  spec:
    selector:
      app: {{ .Values.svc.onechan.name }}
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: onion
      protocol: TCP
      port: 81
      targetPort: 81
    clusterIP: None

kind: List
metadata:
  name: "onechan-list"
