apiVersion: apps/v1
items:

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: {{ .Release.Name }}-{{ .Values.svc.redis.name }}
    namespace: {{ .Release.Namespace }}
  spec:
    replicas: {{ .Values.svc.redis.image.replicas }}
    selector:
      matchLabels:
        app: {{ .Values.svc.redis.name }}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: {{ .Values.svc.redis.name }}
      spec:
        hostname: {{ .Values.svc.redis.name }}
        restartPolicy: {{ .Values.restartPolicy }}
        containers:
        - name: {{ .Values.svc.redis.image.name }}
          image: {{ .Values.svc.redis.image.name }}:{{ .Values.svc.redis.image.tag }}
          imagePullPolicy: {{ .Values.svc.redis.image.pullPolicy }}
          ports:
          - containerPort: 6379
          volumeMounts:
          - name: {{ .Values.svc.redis.name }}-pv
            mountPath: /data
            subPath: redis_data
        volumes:
        - name: {{ .Values.svc.redis.name }}-pv
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ .Values.svc.redis.name }}-pvc

- apiVersion: v1
  kind: Service
  metadata:
    name: {{ .Values.svc.redis.name }}
    namespace: {{ .Release.Namespace }}
  spec:
    selector:
      app: {{ .Values.svc.redis.name }}
    clusterIP: None

kind: List
metadata:
  name: "redis-list"
