name: CI

on:
  push:
    tags:
      - "v*"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
# Build
      -
        name: Build 1chan
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/1chan:latest
          docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE . --push -f ./Dockerfile
