name: CI

on:
  push:
    tags:
      - "v*"

env:
  1CHAN_IMAGE_NAME: 1chan
  SERVICE_IMAGE_NAME: 1chan-service
  TORGATE_IMAGE_NAME: torgate
  I2PGATE_IMAGE_NAME: i2pgate
  YGGDRASILGATE_IMAGE_NAME: yggdrasil

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
# Build
      -
        name: Build 1chan
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/$1CHAN_IMAGE_NAME:latest
          docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE . --push -f ./docker/$1CHAN_IMAGE_NAME.Dockerfile
      -
        name: Build 1chan-service
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/$SERVICE_IMAGE_NAME:latest
          docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE . --push -f ./docker/$SERVICE_IMAGE_NAME.Dockerfile
      -
        name: Build torgate
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/$TORGATE_IMAGE_NAME:latest
          docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE . --push -f ./docker/$TORGATE_IMAGE_NAME.Dockerfile
      -
        name: Build i2pgate
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/$I2PGATE_IMAGE_NAME:latest
          docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE . --push -f ./docker/$I2PGATE_IMAGE_NAME.Dockerfile
      -
        name: Build yggdrasilgate
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/$YGGDRASILGATE_IMAGE_NAME:latest
          docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE . --push -f ./docker/$YGGDRASILGATE_IMAGE_NAME.Dockerfile
