name: CI

on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'

jobs:
  call-docker-build:
    uses: ./.github/workflows/docker-build.yml
    if: github.event.pull_request.merged == true
  call-helm-build:
    uses: ./.github/workflows/helm-build.yml
    if: github.event.pull_request.merged == true
