name: Docker build

on: workflow_call

env:
  ONECHAN_IMAGE_NAME: 1chan
  TORGATE_IMAGE_NAME: torgate
  I2PGATE_IMAGE_NAME: i2pgate
  YGGDRASILGATE_IMAGE_NAME: yggdrasil

jobs:
  buildDocker:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
    
    # Prepare
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
    # Build
      -
        name: Build 1chan
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/1chan.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.ONECHAN_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build torgate
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/torgate.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.TORGATE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build i2pgate
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/i2pgate.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.I2PGATE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build yggdrasilgate
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/yggdrasil.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.YGGDRASILGATE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
