name: Docker build

on: pull_request

env:
  ONECHAN_IMAGE_NAME: 1chan
  TORGATE_IMAGE_NAME: torgate
  I2PGATE_IMAGE_NAME: i2pgate
  YGGDRASILGATE_IMAGE_NAME: yggdrasil

jobs:

  diff:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      buildDocker: ${{ steps.diff.outputs.buildDocker }}
    steps:
    - uses: dorny/paths-filter@v3
      id: diff
      with:
        filters: |
          buildDocker:
            - 'app/**'
            - 'docker/**'
            - 'resources/**'
            - 'scripts/**'
            - 'www/**'

  buildDocker:
    runs-on: ubuntu-latest
    if: ${{ needs.diff.outputs.buildDocker == 'true' }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            onechan:
              - 'app/**'
              - 'resources/**'
              - 'scripts/**'
              - 'www/**'
              - 'docker/1chan.Dockerfile'
              - 'docker/config/1chan/*'
            torgate:
              - 'docker/torgate.Dockerfile'
              - 'docker/config/torgate/*'
            i2pgate:
              - 'docker/i2pgate.Dockerfile'
              - 'docker/config/i2pgate/*'
            yggdrasilgate:
              - 'docker/yggdrasil.Dockerfile'
              - 'docker/config/yggdrasil/*'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      -
        name: Build 1chan
        uses: docker/build-push-action@v5
        if: steps.filter.outputs.onechan == 'true'
        with:
          context: .
          file: docker/1chan.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.ONECHAN_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      -
        name: Build torgate
        uses: docker/build-push-action@v5
        if: steps.filter.outputs.torgate == 'true'
        with:
          context: .
          file: docker/torgate.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.TORGATE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      -
        name: Build i2pgate
        uses: docker/build-push-action@v5
        if: steps.filter.outputs.i2pgate == 'true'
        with:
          context: .
          file: docker/i2pgate.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.I2PGATE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      -
        name: Build yggdrasilgate
        uses: docker/build-push-action@v5
        if: steps.filter.outputs.yggdrasilgate == 'true'
        with:
          context: .
          file: docker/yggdrasil.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.YGGDRASILGATE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
